---

- name: Add the Redis PPA
  become: yes
  apt_repository:
    repo: ppa:chris-lea/redis-server
    update_cache: yes

- name: Install Redis
  become: yes
  apt:
    pkg: redis-server
    state: latest
    update_cache: yes

- name: Ensure that Redis is running
  become: yes
  service:
    name: redis-server
    state: running
