---

- name: Install Python dependencies
  become: yes
  apt:
    pkg: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    - htop
    - git
    - python-virtualenv
    - python3-dev
    - libpq-dev
    - libxslt1-dev
    - libxml2-dev

- name: Create the project directory
  become: yes
  file:
    path: '{{ stacks_src }}'
    group: '{{ ansible_ssh_user }}'
    owner: '{{ ansible_ssh_user }}'
    state: directory

- name: Create the config directory
  become: yes
  file:
    path: /etc/stacks
    group: '{{ ansible_ssh_user }}'
    owner: '{{ ansible_ssh_user }}'
    state: directory

- name: Pull the source code
  git:
    repo: '{{ stacks_repo }}'
    version: '{{ stacks_branch }}'
    dest: '{{ stacks_src }}'
    accept_hostkey: yes

- name: Push the config files
  template:
    src: stacks/{{ item }}.yml.j2
    dest: /etc/stacks/{{ item }}.yml
  with_items:
    - stacks
    - stacks.test

- name: Install pip dependencies
  pip:
    requirements: '{{ stacks_src }}/requirements.txt'
    virtualenv: '{{ stacks_src }}/env'
    virtualenv_python: python3
    state: latest

- name: Install the package
  command: env/bin/python setup.py develop
  args:
    chdir: '{{ stacks_src }}'

- name: Migrate the database
  command: env/bin/alembic upgrade head
  args:
    chdir: '{{ stacks_src }}'

- name: Push startup scripts
  template:
    src: supervisor/{{ item }}.j2
    dest: '{{ stacks_src }}/env/bin/{{ item }}'
    mode: 0755
  with_items:
    - start-manager-dev
    - start-queue-dev
    - start-rqworker
