---

- name: Provision a Django box
  hosts: localhost

  vars_files:
    - vars/local.yml

  tasks:

    - name: Start the server
      register: web
      ec2:

        region: '{{ ec2_region }}'
        image: '{{ ec2_image }}'
        vpc_subnet_id: '{{ ec2_subnet }}'
        keypair: '{{ ec2_keypair }}'

        instance_type: '{{ ec2_instance_type }}'
        group: '{{ ec2_group }}'
        exact_count: '{{ ec2_count }}'

        assign_public_ip: yes
        wait: yes

        volumes:
          - device_name: /dev/sda1
            volume_size: '{{ ec2_root_volume_size }}'

        instance_tags:
          Name: stacks
          context: '{{ ec2_context }}'
          stacks: web

        count_tag:
          context: '{{ ec2_context }}'
          stacks: web

    - name: Attach the data volume
      ec2_vol:

        instance: '{{ item.id }}'
        region: '{{ ec2_region }}'

      with_items: web.instances
