---

- name: Install dependencies
  become: yes
  apt:
    pkg: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    - htop
    - git
    - python3-dev
    - python-virtualenv
    - libpq-dev
    - libxslt1-dev
    - libxml2-dev

- name: Create the project directory
  become: yes
  file:
    path: '{{ stacks_src_dir }}'
    group: '{{ ansible_ssh_user }}'
    owner: '{{ ansible_ssh_user }}'
    state: directory

- name: Create the config directory
  become: yes
  file:
    path: /etc/stacks
    group: '{{ ansible_ssh_user }}'
    owner: '{{ ansible_ssh_user }}'
    state: directory

- name: Pull the source code
  git:
    repo: '{{ stacks_repo }}'
    version: '{{ stacks_branch }}'
    dest: '{{ stacks_src_dir }}'
    accept_hostkey: yes

- name: Push the config files
  template:
    src: stacks/{{ item }}.yml.j2
    dest: /etc/stacks/{{ item }}.yml
  with_items:
    - stacks
    - stacks.test

- name: Install pip dependencies
  pip:
    requirements: '{{ stacks_src_dir }}/requirements.txt'
    virtualenv: '{{ stacks_src_dir }}/env'
    virtualenv_python: python3
    state: latest

- name: Install the package
  command: env/bin/python setup.py develop
  args:
    chdir: '{{ stacks_src_dir }}'
