---

- name: Install dependencies
  become: yes
  apt:
    pkg: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:

    - htop
    - git

    # python
    - python3-dev
    - libboost-python-dev
    - python-virtualenv
    - libpq-dev

    # lxml
    - libxslt1-dev
    - libxml2-dev

    # sqlite
    - sqlite3
    - libsqlite3-dev

    # mpi
    - libcr-dev
    - mpich2
    - mpich2-doc

- name: Create the project directories
  become: yes
  file:
    path: '{{ item.value }}'
    group: '{{ ansible_ssh_user }}'
    owner: '{{ ansible_ssh_user }}'
    state: directory
  with_dict: '{{ stacks_dirs }}'

- name: Create the config directory
  become: yes
  file:
    path: /etc/stacks
    group: '{{ ansible_ssh_user }}'
    owner: '{{ ansible_ssh_user }}'
    state: directory

- name: Pull the source code
  git:
    repo: '{{ stacks_repo }}'
    version: '{{ stacks_branch }}'
    dest: '{{ stacks_dirs.src }}'
    accept_hostkey: yes

- name: Push the config files
  template:
    src: stacks/{{ item }}.yml.j2
    dest: /etc/stacks/{{ item }}.yml
  with_items:
    - stacks
    - stacks.test

- name: Install pip dependencies
  pip:
    requirements: '{{ stacks_dirs.src }}/requirements.txt'
    virtualenv: '{{ stacks_dirs.src }}/env'
    virtualenv_python: python3
    state: latest

- name: Install the package
  command: env/bin/python setup.py develop
  args:
    chdir: '{{ stacks_dirs.src }}'

- name: Create the database
  command: env/bin/inv init_db
  args:
    chdir: '{{ stacks_dirs.src }}'
