---

stacks_repo: git@github.com:davidmcclure/stacks.git
stacks_branch: master

stacks_group: malgeehe

stacks_dirs:
  cfg: /share/PI/malgeehe/config/stacks
  src: /share/PI/malgeehe/code/stacks
  raw: /scratch/PI/malgeehe/data/stacks/raw
  ext: /scratch/PI/malgeehe/data/stacks/ext

stacks_db: /scratch/PI/malgeehe/data/stacks/metadata.db
