---

dependencies:


  - role: data

  - role: redis


  - role: postgresql
    tags: postgresql
    become: yes

    postgresql_version: 9.5

    postgresql_databases:

      - name: '{{ stacks_db_name }}'
      - name: '{{ stacks_test_db_name }}'

    postgresql_users:

      - name: '{{ stacks_db_user }}'
        pass: '{{ stacks_db_pass }}'

    postgresql_user_privileges:

      - name: '{{ stacks_db_user }}'
        db:   '{{ stacks_db_name }}'

        priv: 'ALL'
        role_attr_flags: 'CREATEDB'

    postgresql_database_extensions:
      - db: '{{ stacks_db_name }}'
        extensions:
          - pgcrypto


  - role: supervisor
    tags: supervisor

    supervisor_programs:

      - name: stacks-manager-dev
        command: '{{ stacks_src }}/env/bin/start-manager-dev'

      - name: stacks-queue-dev
        command: '{{ stacks_src }}/env/bin/start-queue-dev'

      - name: rqworker
        command: '{{ stacks_src }}/env/bin/start-rqworker'
        config:
          numprocs: '{{ stacks_rqworker_count }}'
